//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCenter3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLES
    {
        public int ID_DETALLE { get; set; }
        public Nullable<int> ID_ENCABEZADO { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public int CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
        public decimal IMPUESTO { get; set; }
        public decimal TOTAL { get; set; }
    
        public virtual ENC_FACTURAS ENC_FACTURAS { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
