//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCenter3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENC_FACTURAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENC_FACTURAS()
        {
            this.DETALLES = new HashSet<DETALLES>();
        }
    
        public int ID_ENCABEZADO { get; set; }
        public Nullable<int> ID_CLIENTES { get; set; }
        public string FACTURA { get; set; }
        public System.DateTime FECHA { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES> DETALLES { get; set; }
    }
}
