//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCenter3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTOS()
        {
            this.DETALLES = new HashSet<DETALLES>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public Nullable<int> ID_CATEGORIA { get; set; }
        public Nullable<int> ID_PROVEEDOR { get; set; }
        public Nullable<int> ID_SUCURSAL { get; set; }
        public string NOMBRE { get; set; }
        public decimal PRECIO { get; set; }
        public int EXISTENCIA { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public System.DateTime FECHA_VENCI { get; set; }
        public string NOTAS { get; set; }
    
        public virtual CATEGORIAS CATEGORIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLES> DETALLES { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
        public virtual SUCURSALES SUCURSALES { get; set; }
    }
}
