//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediCenter3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int ID_USUARIOS { get; set; }
        public Nullable<int> ID_EMPLEADO { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASENIA { get; set; }
        public string CONFIRMA_CONTRA { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
